.ds AU Douglas Laing, Sergey Poznyakoff \fB<\fRgray@gnu.org\fB>\fR
.if \n(mo=1 .ds mo January
.if \n(mo=2 .ds mo February
.if \n(mo=3 .ds mo March
.if \n(mo=4 .ds mo April
.if \n(mo=5 .ds mo May
.if \n(mo=6 .ds mo June
.if \n(mo=7 .ds mo July
.if \n(mo=8 .ds mo August
.if \n(mo=9 .ds mo September
.if \n(mo=10 .ds mo October
.if \n(mo=11 .ds mo November
.if \n(mo=12 .ds mo December
.nr y4 \n(yr+1900
.ds DA \*(mo \n(dy, \n(y4
.de De
MIX tools are fully documented in the texinfo documentation.
To get \fB\\$1\fR usage information, use
.PP
\fBinfo --usage \\$1\fR
.PP
To read complete \fB\\$1\fR documentation, type
.PP
\fBinfo \\$1\fR
.PP
To read entire \fBMIX\fR manual, type
.PP
\fBinfo mix
.PP
The online copy of the documentation is available from the following address:
.PP
http://mix.software.gnu.org.ua/manual.
..
